default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: abid
  password: password
  host: mysql_book  # Use Docker service name as the host

development:
  <<: *default
  database: book_app_development

test:
  <<: *default
  database: book_app_test

production:
  <<: *default
  database: book_app_production